config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"
  resources :calendars
  resources :operations
  post '/application/guest_sign_in', to: 'application#new_guest'
  get 'prototypes/search'
  get 'prototypes/search'
  resources :books 
  resources :users
  resources :prototypes do
    resources :comments, only: :create 
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @prototypes = Prototype.all
    @books = Book.all
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.create(prototype_params)
    if @prototype.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to prototype_path
    else
      render :edit
    end
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    redirect_to root_path if @prototype.destroy
  end

  private

  def prototype_params
    params.require(:prototype).permit(:title, :text, :concept, :appli, :github, :genre_id, :image).merge(user_id: current_user.id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @prototype.user
  end
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
<%= render 'layouts/error_messages', model: f.object %>
  
  <div class="field">
    <%= f.label :title, "アプリの名称" %><span class="indispensable">必須</span><br />

    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text, "紹介文" %><span class="indispensable">必須</span><br />
    <%= f.text_area :text, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><span class="indispensable">必須</span><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :appli, "アプリのURL" %><span class="indispensable">必須</span><br />
    <%= f.text_area :appli, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :github, "GitHub" %><span class="indispensable">必須</span><br />
    <%= f.text_area :github, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :genre, "ジャンル" %><span class="indispensable">必須</span><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"form__text"}) %>
  </div>

  <div class="field">
    <%= f.label :image, "アプリの画像" %><span class="indispensable">必須</span><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
  <%=link_to 'もどる', root_path, class:"back-btn" %>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to prototype_path(prototype.id),method: :get do %>
  <%= image_tag prototype.image.variant(resize: '300x300'), class: :card__img if prototype.image.attached? %>
 <% end %>
  <div class="card__body">
     <%= link_to  prototype.title, prototype_path(prototype.id), class: :card__title%>
     <%= link_to  "作成者：#{prototype.user.name}", user_path(prototype.user.id), class: :artist__title %>
    <p class="card__summary">
  
    </p>
    <%= prototype.genre.name %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">アプリの編集</h2>
      <%= render partial: "form", locals: {prototype: @prototype} %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<div class='title-contents'>
    <h2 class='service-title'>
      集え！＃駆け出しエンジニア！
    </h2>
    <p class='service-explain'>
      Mentoreはエンジニア転職を目指す
    </p>
    <p class='service-explain'>
      仲間を増やせるマッチングアプリです！<%#= link_to 'ゲストログイン（閲覧用）',  application_guest_sign_in_path, method: :post, class: :guest__btn %>
    </p>
</div>

  <div class='feature-contents'>
    <h2 class='title'>
      こんな方にオススメ！
    </h2>
  </div>  

  <div class="persona__wrapper">
    <%= image_tag("top_img1.png", class: :logo) %>    
    <%= image_tag("top_img2.png", class: :logo) %>
    <%= image_tag("top_img3.png", class: :logo) %>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>まずは、無料でもサービスを使いたい</p>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>エンジニア初学者同士で気軽に交流をしたい</p>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>SNS等でお互いのことを知った上で、安心・安全に繋がりたい！</p>
  </div>
  
  <div class='feature-contents'>
    <h2 class='title'>
      Mentoreの特徴
    </h2>
  </div>

  <div class="personan__wrapper">
    <%= link_to image_tag("top_img4.png", class: :logo), new_prototype_path %>
    <%= link_to image_tag("top_img5.png", class: :logo), calendars_path %>
    <%= link_to image_tag("top_img6.png", class: :logo), new_book_path %>
    <%= link_to image_tag("top_img7.png", class: :logo), operations_path %>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>初学者のポートフォリオとGitHubを見れる</p>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>お互いに緊張感が持てる、面接練習したい相手を募集する</p>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>最近、読んだ技術書やビジネス書の感想を投稿できる！</p>
    <p class='text-explain'><%= image_tag("point4.png", class: :stepup) %>転職サポートプラン（有料）では専任エージェントによるサポートを受けられます！</p>
  </div>

  <div class='work-contents'>
    <h2 class='title'>ポートフォリオ</h2>
  </div>  

  <div class="card__wrapper">
    <%= render partial: 'prototype', collection: @prototypes %>
  </div>  

    <div class='work-contents'>
    <h2 class='title'>ITエンジニア本</h2>
  </div>  

  <div class="card__wrapper">
    <%= render partial: 'books/book', collection: @books %>
  </div>  

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規アプリ投稿<%= image_tag("top_img4.png", class: :top) %></h2>
        <%= render partial: "form", locals: {prototype: @prototype} %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <p class="genre__hedding">
        <%= @prototype.genre.name %>
      </p>
      
      <%= link_to "作成者：#{@prototype.user.name}", user_path(@prototype.user), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>  
      
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">紹介文</p>
          <p class="detail__message">
            <%= @prototype.text %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">ポートフォリオ</p>
          <h1 class="detail__message">
            <%= link_to "アプリを確認する", @prototype.appli, class: :prototype__btn %>
            <%= link_to "GitHubを確認する", @prototype.github, class: :prototype__btn %>
          </h1>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@prototype, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><%= image_tag("like.png", class: :top) %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :comment__btn  %>
            </div>
          <% end %> 
        <% end %>  

        <ul class="comments_lists">            
              <% if @comments %>
                <% @comments.each do |comment| %>
                <li class="comments_list">
                <%= comment.text %>
                <%= link_to comment.user.name,  "/users/#{comment.user_id}", class: :comment_user %>             
                <% end %>
            <% end %>
            </li>
        </ul>
      </div>
    </div>
  </div>
</main>