config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"
  resources :calendars
  resources :operations
  post '/application/guest_sign_in', to: 'application#new_guest'
  get 'prototypes/search'
  get 'prototypes/search'
  resources :books 
  resources :users
  resources :prototypes do
    resources :comments, only: :create 
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true
  validates :understand, presence: true
  validates :text, presence: true
  validates :link, presence: true
  validates :image, presence: true, unless: :was_attached?

  validates :link, format: { with: /amazon.co.jp/ }

  def was_attached?
    image.attached?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    redirect_to root_path if @book.destroy
  end

  private

  def book_params
    params.require(:book).permit(:title, :reed, :understand, :text, :action, :link, :image).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @book.user
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_book.html.erb
<div class="card">
  <%= link_to book_path(book.id),method: :get do %>
  <%= image_tag book.image.variant(resize: '300x300'), class: :card__img if book.image.attached? %>
 <% end %>
  <div class="card__body">
     <%= link_to  book.title, book_path(book.id), class: :card__title%>
     <%= link_to  "投稿者：#{book.user.name}", user_path(book.user.id), class: :artist__title %>
    <p class="card__summary">
      <%= book.understand %>   
    </p>
  </div>
</div>

app/views/books/_memo.html.erb
<%= form_with model: @book, local: true do |f|%>
<%= render 'layouts/error_messages', model: f.object %>
  
  <div class="field">
    <%= f.label :title, "本のタイトル" %><span class="indispensable">必須</span><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :reed, "本の種類" %><span class="indispensable">必須</span><br />
    <%= f.text_area :reed, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :understand, "学んだ単語" %><span class="indispensable">必須</span><br />
    <%= f.text_area :understand, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :text, "本の感想" %><span class="indispensable">必須</span><br />
    <%= f.text_area :text, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :action, "行動プラン" %><br />
    <%= f.text_area :action, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :link, "KindleのURL" %><span class="indispensable">必須</span><br />
    <%= f.text_area :link, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "Kindleの画像" %><span class="indispensable">必須</span><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
  <%=link_to 'もどる', root_path, class:"back-btn" %>
<% end %>

app/views/books/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">読んだ本の編集</h2>
      <%= render partial: "memo", locals: {book: @book} %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='feature-contents'>
    <h2 class='title'>技術書</h2>
  </div>  

  <div class="card__wrapper">
    <%#= render partial: 'prototype', collection: @prototypes %>
  </div>  

app/views/books/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">読んだ本を投稿<%= image_tag("top_img6.png", class: :top) %></h2>
        <%= render partial: "memo", locals: {book: @book} %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
      <%= image_tag("top_img6.png", class: :top) %>
        <%= @book.title %>
      </p>
      
      <%= link_to "投稿者：#{@book.user.name}", user_path(@book.user), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @book.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_book_path(@book.id), class: :prototype__btn %>
          <%= link_to "削除する", book_path(@book.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>  
      
      <div class="prototype__image">
        <%= image_tag @book.image %>
      </div>
        <div class="prototype__detail">
          <p class="detail__title">学んだ単語</p>
          <p class="detail__message">
            <%= @book.understand %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">本の感想</p>
          <p class="detail__message">
            <%= @book.text %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title"></p>
          <h1 class="detail__message">
            <%= link_to "Kindleで確認する", @book.link, class: :prototype__btn %>
          </h1>
        </div>
      </div>



      </div>
    </div>
  </div>
</main>